Hyperledger AnonCreds 2023Q2 Quarterly Report
hyperledger/tsc pull request #100
Opened 2023-05-01 19:03 UTC by swcurran

Signed-off-by: Stephen Curran <swcurran@gmail.com>

2023-05-01 21:35 UTC, tkuhrt requested changes

2023-05-01 21:35 UTC, tkuhrt commented on project-reports/2023/2023-Q2-Hyperledger-AnonCreds.md
> +- [anoncreds-rs] -- [v0.1.0-dev.1] through [v0.1.0-dev12] (12 releases)
```suggestion
- [anoncreds-rs] -- [v0.1.0-dev.1] through [v0.1.0-dev.12] (12 releases)
```

2023-05-01 21:35 UTC, tkuhrt commented on project-reports/2023/2023-Q2-Hyperledger-AnonCreds.md
> +presentations, plus a potential revocation scheme ([ALLOSSAUR], [ALLOSAUR Summary]) that could be
```suggestion
presentations, plus a potential revocation scheme ([ALLOSAUR], [ALLOSAUR Summary]) that could be
```

2023-05-02 10:41 UTC, TimoGlastra approved these changes

2023-05-04 08:31 UTC, arsulegai approved these changes

2023-05-04 13:53 UTC, VRamakrishna commented on project-reports/2023/2023-Q2-Hyperledger-AnonCreds.md
> +The AnonCreds project has has significant progress on three fronts this quarter:
"has has" --> "has made"

2023-05-04 13:56 UTC, VRamakrishna commented on project-reports/2023/2023-Q2-Hyperledger-AnonCreds.md
> +that should be a straight forward transfer of code from the existing Ursa
"straight forward" --> "straightforward".

2023-05-04 13:56 UTC, tkuhrt approved these changes

2023-05-04 13:57 UTC, VRamakrishna approved these changes

2023-05-04 14:04 UTC, denyeart approved these changes

2023-05-04 15:24 UTC, bobbi28 approved these changes

2023-05-04 17:00 UTC, jimthematrix approved these changes

2023-05-10 12:47 UTC, mbrandenburger approved these changes

2023-05-15 20:15 UTC, merged