Add Caliper 2023 Q3 project status report
hyperledger/tsc pull request #173
Opened 2023-10-16 18:44 UTC by aklenik

2023-10-17 00:04 UTC, petermetz approved these changes

2023-10-17 06:35 UTC, denyeart approved these changes

2023-10-17 12:18 UTC, lehors approved these changes

2023-10-17 15:56 UTC, tkuhrt requested changes

2023-10-17 15:56 UTC, tkuhrt commented on project-reports/2023/2023-Q3-Hyperledger-Caliper.md
> +title: Project Name
```suggestion
title: 2023 Q3 Hyperledger Caliper
```

2023-10-18 01:41 UTC, jimthematrix approved these changes

2023-10-18 13:24 UTC, VRamakrishna approved these changes

2023-10-18 13:43 UTC, swcurran approved these changes

2023-10-18 15:50 UTC, tkuhrt approved these changes

2023-10-19 01:09 UTC, bobbi28 approved these changes

2023-10-19 23:19 UTC, mbrandenburger approved these changes

2023-10-20 21:56 UTC, yeasy commented on project-reports/2023/2023-Q3-Hyperledger-Caliper.md
> +The activity has been minimal in the last quarter due to the maintainers being otherwise engaged. The mentorship is expected to reignite the activity around Caliper. Moreover, there's an ongoing disc
Would be interesting to see performance report with latest versions.

2023-10-31 16:59 UTC, merged

2024-01-25 09:21 UTC, davidkel commented on project-reports/2023/2023-Q3-Hyperledger-Caliper.md
> +The activity has been minimal in the last quarter due to the maintainers being otherwise engaged. The mentorship is expected to reignite the activity around Caliper. Moreover, there's an ongoing disc
@yeasy that's upto Hyperledger Fabric and whether they wish to use Caliper as a Load Generator and Reporter. It was used in the past for a Performance blog and this covered Hyperledger Fabric 2.5. You can find the blog here https://www.hyperledger.org/blog/2023/02/16/benchmarking-hyperledger-fabric-2-5-performance