2024 update calendar
hyperledger/tsc pull request #176
Opened 2023-10-25 14:44 UTC by ryjones

Adding updates for 2024

2023-10-28 20:32 UTC, ryjones commented
@tkuhrt plz review

2023-10-30 16:32 UTC, tkuhrt requested changes

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q2      | 2024-05-16 | Bevel     |
```suggestion
| Q2      | 2024-05-16 | Bevel     |
| Q2      | 2024-05-23 | Transact  |
| Q2      | 2024-05-23 | Solang    |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q3      | 2024-08-22 | Solang    |
```suggestion
| Q3      | 2024-08-22 | Transact  |
| Q3      | 2024-08-22 | Solang    |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q4      | 2024-11-07 | AnonCreds |
```suggestion
| Q4      | 2024-11-07 | AnonCreds |
| Q4      | 2024-11-07 | Iroha     |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q4      | 2024-11-21 | Solang    |
```suggestion
| Q4      | 2024-11-21 | Transact  |
| Q4      | 2024-11-21 | Solang    |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q4      | 2024-12-05 | Firefly   |
```suggestion
| Q4      | 2024-12-05 | Firefly   |
| Q4      | 2024-12-05 | Besu      |
| Q4      | 2024-12-05 | Caliper   |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q1      | 2024-01-10 | Cacti     |
```suggestion
| Q1      | 2024-01-11 | Cacti     |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q1      | 2024-01-10 | Fabric    |
```suggestion
| Q1      | 2024-01-11 | Fabric    |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q1      | 2024-01-24 | Sawtooth  |
```suggestion
| Q1      | 2024-01-25 | Sawtooth  |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q1      | 2024-01-31 | AnonCreds |
```suggestion
| Q1      | 2024-02-01 | Aries     |
| Q1      | 2024-02-01 | Indy      |
| Q1      | 2024-02-01 | AnonCreds |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q1      | 2024-02-07 | Iroha     |
```suggestion
| Q1      | 2024-02-08 | Iroha     |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q1      | 2024-02-14 | Bevel     |
```suggestion
| Q1      | 2024-02-15 | Bevel     |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024-updated.md
> +| Q1      | 2024-02-21 | Solang    |
```suggestion
| Q1      | 2024-02-22 | Transact  |
| Q1      | 2024-02-22 | Solang    |
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q1,2024-01-10,Fabric
```suggestion
Q1,2024-01-11,Cacti
Q1,2024-01-11,Fabric
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q1,2024-01-24,Sawtooth
```suggestion
Q1,2024-01-25,Sawtooth
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q1,2024-01-31,AnonCreds
```suggestion
Q1,2024-02-01,Aries
Q1,2024-02-01,Indy
Q1,2024-02-01,AnonCreds
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q1,2024-02-07,Iroha
```suggestion
Q1,2024-02-08,Iroha
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q1,2024-02-14,Bevel
```suggestion
Q1,2024-02-15,Bevel
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q1,2024-02-21,Solang
```suggestion
Q1,2024-02-22,Transact
Q1,2024-02-22,Solang
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q2,2024-05-16,Bevel
```suggestion
Q2,2024-05-16,Bevel
Q2,2024-05-23,Transact
Q2,2024-05-23,Solang
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q3,2024-08-22,Solang
```suggestion
Q3,2024-08-22,Transact
Q3,2024-08-22,Solang
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q4,2024-11-07,AnonCreds
```suggestion
Q4,2024-11-07,AnonCreds
Q4,2024-11-07,Iroha
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q4,2024-11-21,Solang
```suggestion
Q4,2024-11-21,Transact
Q4,2024-11-21,Solang
```

2023-10-30 16:32 UTC, tkuhrt commented on project-reports/2024/2024.csv
> +Q4,2024-12-05,Firefly
```suggestion
Q4,2024-12-05,Firefly
Q4,2024-12-05,Besu
Q4,2024-12-05,Caliper
```

2023-10-30 18:57 UTC, ryjones commented
@tkuhrt if this is ready, go ahead and merge

2023-10-31 17:00 UTC, tkuhrt approved these changes

2023-10-31 17:08 UTC, merged