Aries 2024 Q2 Quarterly Report
hyperledger/tsc pull request #243
Opened 2024-05-02 18:31 UTC by swcurran

Signed-off-by: Stephen Curran <swcurran@gmail.com>

2024-05-03 17:06 UTC, petermetz approved these changes
LGTM

2024-05-06 15:24 UTC, tkuhrt requested changes

2024-05-06 15:24 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-Aries.md
> +[BBS Signatures Go]: aries-bbs-go
```suggestion
[BBS Signatures Go]: https://github.com/hyperledger/aries-bbs-go
```

2024-05-06 15:24 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-Aries.md
> +  replacements ([Aries Askar], [Indy VDR], and [AnonCreds-RS]). Good to see that
Don't see a link for Indy VDR.

2024-05-06 15:24 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-Aries.md
> +  replacements ([Aries Askar], [Indy VDR], and [AnonCreds-RS]). Good to see that
Similarly, for AnonCreds-RS.

2024-05-06 15:24 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-Aries.md
> +  [Credo-TS] and [Bifold Wallet], with the PR to add support in [ACA-Py]
Don't see a link for ACA-Py

2024-05-06 15:24 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-Aries.md
> +* Work has begun on adding [DIDComm v2] support in [ACA-Py].
Don't see a link for DIDComm v2

2024-05-06 15:24 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-Aries.md
> +but has no longer funded. To be determined if someone else picks up the work, or if
```suggestion
but is no longer funded. To be determined if someone else picks up the work, or if
```

2024-05-08 13:26 UTC, denyeart commented on project-reports/2024/2024-Q2-Hyperledger-Aries.md
> +In 2023Q3 there were contributions from 64 individuals representing at least 18 organizations.
2023Q3?

2024-05-08 13:56 UTC, swcurran commented
Problems in Markdown and typos corrected -- thanks for checking, sorry for not using lint.

2024-05-08 16:43 UTC, non-fungible-nelson commented
LGTM, great job on diversity of contributors

2024-05-08 16:43 UTC, non-fungible-nelson approved these changes

2024-05-08 17:47 UTC, tkuhrt approved these changes

2024-05-10 02:48 UTC, denyeart approved these changes

2024-05-14 08:11 UTC, mbrandenburger approved these changes

2024-05-23 14:20 UTC, jimthematrix approved these changes

2024-05-23 15:47 UTC, merged