AnonCreds Quarterly Report - 2024Q2
hyperledger/tsc pull request #245
Opened 2024-05-03 23:15 UTC by swcurran

Signed-off-by: Stephen Curran <swcurran@gmail.com>

2024-05-03 23:19 UTC, petermetz approved these changes

2024-05-06 15:32 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-AnonCreds.md
> +Verifiable Credential Data Model ([VCDM]) format. This was triggered by a "Code
Is [VCDM] supposed to be a link?

2024-05-06 15:35 UTC, tkuhrt requested changes

2024-05-06 15:35 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-AnonCreds.md
> +With Us" procurement from BC Gov that was won by [DSR Corporation] for the
Missing link for [DSR Corporation]

2024-05-06 15:35 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-AnonCreds.md
> +[AnonCreds Rust] work, [Animo Solutions] for the adding support for the format
Missing link for [Animo Solutions]

2024-05-06 15:35 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-AnonCreds.md
> +JavaScript and Aries Bifold React Native, respectively and now part of the [Open
Missing link for [Open Wallet Foundation]

2024-05-06 15:35 UTC, tkuhrt commented on project-reports/2024/2024-Q2-Hyperledger-AnonCreds.md
> +Wallet Foundation]), and What's Cookin for adding support the for the format in
```suggestion
Wallet Foundation]), and What's Cookin for adding support for the format in
```

2024-05-08 14:09 UTC, denyeart approved these changes

2024-05-08 14:22 UTC, swcurran commented on project-reports/2024/2024-Q2-Hyperledger-AnonCreds.md
> +Verifiable Credential Data Model ([VCDM]) format. This was triggered by a "Code
Yes - fixed

2024-05-08 17:50 UTC, tkuhrt approved these changes

2024-05-14 20:44 UTC, mbrandenburger approved these changes

2024-05-23 15:43 UTC, jimthematrix approved these changes

2024-05-30 13:33 UTC, VRamakrishna approved these changes

2024-05-30 13:44 UTC, merged