fix typos in documentation files
hyperledger/tsc pull request #311
Opened 2024-11-09 10:59 UTC by futreall

In this pull request, the following changes were made:

1. **File `raising-an-issue.md`**:
   - Fixed typo: corrected "equiped" to "equipped".
   - Updated link to TOC members, changing `../members-info/toc-members.md` to `../member-info/toc-members.md`.

2. **File `index.md`** (in `project-reports` directory):
   - Added "Whether" at the beginning of the first list item under "Project updates are:" for clarity.
   - Fixed numbering in "Instructions for Filing" section, changing "1." to "2." for logical sequencing.

2024-11-10 19:03 UTC, petermetz approved these changes

2024-11-11 14:35 UTC, tkuhrt commented on project-reports/index.md
> +Whether the project updates are:
This is not a correct change. Please revert changes to this file as none are needed.

2024-11-11 14:36 UTC, tkuhrt requested changes
Thanks for finding the spelling mistake. Please update as specified.

2024-11-11 15:15 UTC, futreall commented
@tkuhrt Accepted your comment and reverted the changes back. Thank you for the clarification !

2024-11-11 15:33 UTC, tkuhrt approved these changes

2024-11-11 15:33 UTC, merged