Add Q1 2023 report for project Cello
hyperledger/tsc pull request #76
Opened 2023-02-28 22:22 UTC by yeasy

2023-03-01 15:50 UTC, tkuhrt requested changes
A few formatting and spelling changes.

2023-03-01 15:50 UTC, tkuhrt commented on project-reports/2023/2023-Q1-Hyperledger-Cello.md
> +[x] Have you added an [Inclusive Language Statement](https://wiki.hyperledger.org/display/TSC/Inclusive+Language+Example) to your project's documentation and/or Wiki pages?
```suggestion
- [x] Have you switched from master to main in all your repos? 
- [x] Have you implemented the [Common Repository Structure](../guidelines/repository-structure.md) in all your repos? 
- [x] Has your project implemented these inclusive language changes listed below to your repo? You can optionally [use the DCI Lint tool](https://github.com/petermetz/gh-action-dci-lint#usage) to make this a recurring action on your repo.
    - master → main
    - slave → replicas
    - blacklist → denylist
    - whitelist → allowlist
- [x] Have you added an [Inclusive Language Statement](https://wiki.hyperledger.org/display/TSC/Inclusive+Language+Example) to your project's documentation and/or Wiki pages?
```

2023-03-01 15:50 UTC, tkuhrt commented on project-reports/2023/2023-Q1-Hyperledger-Cello.md
> +* v1.0.0-GA is planed in Q1, 2023.
```suggestion
* v1.0.0-GA is planned in Q1, 2023.
```

2023-03-01 15:50 UTC, tkuhrt commented on project-reports/2023/2023-Q1-Hyperledger-Cello.md
> +Current there are 3 maintainers, and those active developers who contribute to cello continuously (3 month) may be nominated as new maintainers.
```suggestion
Current there are 3 maintainers, and those active developers who contribute to Cello continuously (3 month) may be nominated as new maintainers. 
```

2023-03-01 23:49 UTC, tkuhrt approved these changes

2023-03-02 05:51 UTC, denyeart approved these changes

2023-03-02 12:42 UTC, lehors approved these changes

2023-03-02 14:39 UTC, bobbi28 approved these changes

2023-03-02 14:51 UTC, swcurran approved these changes

2023-03-06 11:48 UTC, VRamakrishna approved these changes

2023-03-07 22:25 UTC, jimthematrix approved these changes

2023-03-08 14:08 UTC, mbrandenburger approved these changes

2023-03-14 17:29 UTC, merged